url: http://pickardayune.com
title: the Pickard Ayune
subtitle: just past Jerkwater Road
author: Matt Burke
simple_search: http://google.com/search

# From https://help.github.com/articles/using-jekyll-with-pages
safe: true
lsi: false

permalink: /blog/:year/:month/:day/:title
paginate: 5
